[project]
name = "cky-parsing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "nltk>=3.8",
]

[dependency-groups]
dev = [
    "ruff>=0.14.6",
]
